version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - mvn install
artifacts:
  files:
    - target/codedeploy.jar
    - appspec.yml
  discard-paths: yes