version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn install
      - cp target/codedeploy.war .
artifacts:
  files:
    - codedeploy.war
    - appspec.yml
    - scripts/*
