version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn install
      - ls
      - ls target
artifacts:
  files:
    - target/codedeploy.war
    - appspec.yml
  discard-paths: yes
